import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const chivo = localFont({
  src: [
    {
      path: "../public/typefaces/ChivoMono-VariableFont_wght.ttf",
      weight: "400",
      style: "normal",
    },

    {
      path: "../public/typefaces/ChivoMono-Italic-VariableFont_wght.ttf",
      weight: "400",
      style: "italic",
    },
  ],
  variable: "--font-chivo",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${chivo.variable} antialiased bg-[var(--shade-900)] text-[var(--shade-50)] selection:bg-[var(--shade-150)] selection:text-black`}
      >
        {children}
      </body>
    </html>
  );
}
